version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html # EC2 인스턴스에 index.html을 배포할 디렉터리입니다.
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
