version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install Apache and dependencies..."
      - sudo yum update -y
      - sudo yum install -y httpd autoconf libtool httpd-devel gcc gcc-c++ wget
  pre_build:
    commands:
      - echo "Download and install Tomcat connector..."
      - cd /tmp && wget https://dlcdn.apache.org/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.49-src.tar.gz
      - tar -xzf /tmp/tomcat-connectors-1.2.49-src.tar.gz
      - cd /tmp/tomcat-connectors-1.2.49-src/native && ./configure --with-apxs=/usr/bin/apxs
      - cd /tmp/tomcat-connectors-1.2.49-src/native && make
      - cd /tmp/tomcat-connectors-1.2.49-src/native && sudo make install
  post_build:
    commands:
      - echo "Starting Apache server..."
      - sudo systemctl start httpd
      - sudo systemctl enable httpd
artifacts:
  files:
    - '**/*'
